%YAML:1.0
---

# 0 红场  1 蓝场
Field: 0 
ShowParams: true
Showtest: false
Kfs_path: "/home/lx/frame/yolo_part2_rotated/1780928132_191145.jpg"

# D455Node parameters
D455Node:
  Display: false
  DispersionThreshold: 800
  Pcl_params:
    white_gray_min: 100
    white_gray_max: 255
    white_hsv_min: [0, 0, 110, 0]
    white_hsv_max: [180, 40, 255, 0]
  ActD_params:
    bag_path: "/home/lx/d455_1781759640.bag"

# Deal parameters
Deal:
  Display: true
  Rect: [314, 214, 39, 11]
  RectFixed: [298, 230, 70, 65]
  IntervalY: 20
  IouThresh: 0.4
  ImagePath: "/home/lx/frame/yolo_52_3/1777710386_255516.jpg"
  VideoPath: "/home/lx/frame/camera_back_2026-05-01_11-19-57_cut_00-02_to_00-17.avi"
